In [1]:
import numpy as np

In [8]:
arr = np.random.randint(0, 10,(2, 2))
arr
arr_2 = arr.reshape(4, 1)
arr_2

array([[9],
       [6],
       [5],
       [4]], dtype=int32)

In [14]:
np.random.seed(seed=1)
arr = np.random.randint(0, 10, (2,5,3))
arr

array([[[5, 8, 9],
        [5, 0, 0],
        [1, 7, 6],
        [9, 2, 4],
        [5, 2, 4]],

       [[2, 4, 7],
        [7, 9, 1],
        [7, 0, 6],
        [9, 9, 7],
        [6, 9, 1]]], dtype=int32)

In [16]:
arr = np.arange(0, 9, 1)
print(f"array: \n {arr} \n\n"
      f"array shape: {arr.shape}")


array: 
 [0 1 2 3 4 5 6 7 8] 

array shape: (9,)


In [24]:
arr_reshape = arr.reshape(-1, 1)
print(f"array: \n {arr_reshape} \n\n"
      f"array shape: {arr_reshape.shape}")

array: 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]] 

array shape: (9, 1)


In [31]:
my_list = [0, 1, 2, 3, 4, 5]
my_list = np.array(my_list)
my_list = my_list.reshape(-3, 3)
my_list
print(f"{my_list} \n\n contains the array shape: {my_list.shape}")

[[0 1 2]
 [3 4 5]] 

 contains the array shape: (2, 3)


In [33]:
arr = np.random.randint(80, 200, (3, 3, 2))
arr


array([[[148, 104],
        [193, 123],
        [156, 106]],

       [[132, 160],
        [189, 195],
        [121, 162]],

       [[ 95, 144],
        [148, 105],
        [191, 178]]], dtype=int32)

In [41]:
arr = arr.reshape(-1, 1)
arr

array([[148],
       [104],
       [193],
       [123],
       [156],
       [106],
       [132],
       [160],
       [189],
       [195],
       [121],
       [162],
       [ 95],
       [144],
       [148],
       [105],
       [191],
       [178]], dtype=int32)

In [45]:
np.random.seed(seed=1)
arr = np.random.randint(0, 100, (2, 3, 4))
arr

array([[[37, 12, 72,  9],
        [75,  5, 79, 64],
        [16,  1, 76, 71]],

       [[ 6, 25, 50, 20],
        [18, 84, 11, 28],
        [29, 14, 50, 68]]], dtype=int32)

In [52]:
task = arr.reshape(-1)
task

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1, 76, 71,  6, 25, 50, 20, 18,
       84, 11, 28, 29, 14, 50, 68], dtype=int32)

In [50]:
task = arr.flatten()
task


array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1, 76, 71,  6, 25, 50, 20, 18,
       84, 11, 28, 29, 14, 50, 68], dtype=int32)

In [51]:
task.shape

(24,)

In [58]:
task.min()


np.int32(1)

In [57]:
task.max()

np.int32(84)

In [60]:
task.argmin()

np.int64(9)

In [62]:
task.argmax()

np.int64(17)

In [67]:
task.argmin(axis=0)

np.int64(9)

In [74]:
arr = np.arange(0, 50, 5).reshape(2, 5)
arr

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [76]:
arr.argmin(axis=0)

array([0, 0, 0, 0, 0])