In [3]:
import numpy as np

In [12]:
arr = np.arange(0, 20, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
arr[4]

np.int64(8)

In [22]:
arr[0:5]

array([0, 2, 4, 6, 8])

In [1]:
arr[3:]

NameError: name 'arr' is not defined

In [11]:
np.random.seed(seed=1)
arr = np.random.randint(0, 11,(2, 5))
arr

array([[5, 8, 9, 5, 0],
       [0, 1, 7, 6, 9]], dtype=int32)

In [21]:
arr.argmin(axis=1)

array([4, 0])

In [24]:
arr[:2]

array([[5, 8, 9, 5, 0],
       [0, 1, 7, 6, 9]], dtype=int32)

In [28]:
arr = np.random.randint(80, 100, 10)
arr

array([97, 91, 92, 96, 93, 99, 89, 98, 95, 80], dtype=int32)

In [31]:
arr [4]

np.int32(93)

In [33]:
arr[:4]

array([97, 91, 92, 96], dtype=int32)

In [35]:
arr[1:8]

array([91, 92, 96, 93, 99, 89, 98], dtype=int32)

In [36]:
arr[9:]

array([80], dtype=int32)

** 2D Arrays

In [43]:
np.random.seed(seed=1)
arr = np.random.randint(1, 800, (4, 6))
arr

array([[ 38, 236,  73, 768, 716, 646],
       [145, 130, 584, 750, 509, 391],
       [282, 179, 277, 255, 358, 469],
       [253, 491, 669, 399, 563, 581]], dtype=int32)

In [ ]:
arr[2,:]

array([282, 179, 277, 255, 358, 469], dtype=int32)

In [50]:
arr[:, 4]

array([716, 509, 358, 563], dtype=int32)

In [54]:
arr[:2, 3:]

array([[768, 716, 646],
       [750, 509, 391]], dtype=int32)

** 3D Array

In [59]:
np.random.seed(seed=0)
arr = np.random.randint(250, 600, (3, 5, 3))
arr

array([[[422, 297, 367],
        [442, 573, 501],
        [445, 259, 461],
        [527, 492, 542],
        [337, 320, 338]],

       [[564, 443, 289],
        [337, 424, 338],
        [587, 415, 275],
        [583, 322, 515],
        [365, 493, 447]],

       [[585, 588, 349],
        [427, 493, 535],
        [397, 397, 538],
        [515, 435, 377],
        [282, 281, 452]]], dtype=int32)

In [71]:
arr [1, 2, 1]

np.int32(415)

In [72]:
arr[2, 4:]

array([[282, 281, 452]], dtype=int32)

In [74]:
arr[1, 2:, 2:]

array([[275],
       [515],
       [447]], dtype=int32)

In [77]:
arr[0:2, :2, :2]

array([[[422, 297],
        [442, 573]],

       [[564, 443],
        [337, 424]]], dtype=int32)