In [2]:
import numpy as np

In [3]:
np.random.seed(seed = 0)
arr = np.random.randint(1, 45,(3, 3))
arr

array([[ 1,  4,  4],
       [40, 10, 20],
       [22, 37, 24]], dtype=int32)

In [7]:
arr[arr>=10]

array([40, 10, 20, 22, 37, 24], dtype=int32)

In [9]:
arr>=10

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
arr[(arr>2) & (arr<40)]

array([ 4,  4, 10, 20, 22, 37, 24], dtype=int32)

In [19]:
arr[((arr>=25)|(arr % 2 == 0) | (arr == 0))]

array([ 4,  4, 40, 10, 20, 22, 37, 24], dtype=int32)

*Break

In [2]:
import numpy as np

In [4]:
np.random.seed(seed=1)
arr = np.random.randint(0, 50, (2, 3, 3))
arr

array([[[37, 43, 12],
        [ 8,  9, 11],
        [ 5, 15,  0]],

       [[16,  1, 12],
        [ 7, 45,  6],
        [25, 20, 37]]], dtype=int32)

In [12]:
arr [1:, :3, 1:2 ]

array([[[ 1],
        [45],
        [20]]], dtype=int32)

In [25]:
arr [arr>30]

array([37, 43, 45, 37], dtype=int32)

In [22]:
arr [((arr % 3 == 0) | (arr >=40) | (arr == 50)) ]

array([43, 12,  9, 15,  0, 12, 45,  6], dtype=int32)