In [3]:
import numpy as np
np.arange(start = 0, stop = 105, step = 5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [ ]:
np.arange(1, 10, 1)

In [ ]:
arr = np.zeros(shape = (3,5), dtype=int)
arr

In [ ]:
print(f"the second item in third row is {arr[2, 3]}")

In [ ]:
arr =np.zeros(shape = (3, 1, 5))
arr

In [ ]:
arr= np.ones(shape=(4,3))
arr

In [ ]:
np.linspace(start = 0, stop = 10, num = 5, dtype=float)


In [ ]:
arr = np.linspace(start=0,stop=9,num=6, dtype=float)
arr

In [ ]:
arr = np.linspace(-3, 5, 9)
arr

In [ ]:
arr= np.random.rand(3, 4)
arr

In [ ]:
arr= np.random.rand()
arr

In [ ]:
arr = np.random.rand(3, 4, 2)
arr

In [ ]:
arr = np.random.randn(4, 5, 2)
arr

In [54]:
arr = np.random.randn(25)
arr

array([-4.83246302e-01,  8.37093670e-01,  1.22555760e+00, -4.33815647e-01,
       -1.64781296e+00,  6.22731995e-01, -1.81098117e+00,  1.20047669e+00,
       -1.03095886e-01,  2.65218496e-01, -1.10318799e-01,  2.28911262e+00,
       -4.59748427e-01, -2.35682204e+00,  6.83517950e-02,  7.22062003e-01,
       -1.32378122e+00,  1.39423743e+00, -4.08612717e-04, -7.76089182e-01,
        2.28870340e-01,  5.78273593e-01, -6.52048662e-01,  8.42929246e-02,
       -1.39441902e+00])

In [53]:
arr = np.random.randint(0, 3, 3)
arr

array([1, 1, 2], dtype=int32)

In [60]:
arr = np.random.randint(456, 890,(3, 3))
arr

array([[575, 546, 496],
       [518, 478, 726],
       [615, 749, 741]], dtype=int32)

In [70]:
arr = np.random.randint(250, 888, (2, 3, 2))
arr

array([[[424, 633],
        [801, 444],
        [791, 623]],

       [[851, 578],
        [301, 766],
        [299, 651]]], dtype=int32)

In [4]:
np.random.seed(seed=2)
arr = np.random.randint(0, 10, (2, 2))
arr

array([[8, 8],
       [6, 2]], dtype=int32)

In [7]:
arr.shape


(2, 2)

In [10]:
arr.sum(axis=0)

array([14, 10])