In [1]:
import numpy as np

In [2]:
np.random.seed(seed=1)
arr = np.random.randint(55, 95, (3, 4, 5))
arr

array([[[92, 67, 63, 64, 66],
        [60, 70, 55, 71, 56],
        [67, 62, 61, 80, 75],
        [92, 73, 75, 66, 83]],

       [[84, 69, 59, 78, 78],
        [85, 87, 77, 68, 64],
        [62, 77, 56, 55, 72],
        [63, 79, 68, 63, 85]],

       [[62, 58, 61, 76, 58],
        [59, 79, 67, 81, 71],
        [73, 70, 55, 59, 80],
        [89, 78, 62, 81, 80]]], dtype=int32)

In [7]:
my_list = np.array([2, 3, 4])
my_list

array([2, 3, 4])

In [16]:
[3* x for x in [2, 3, 4]]

[6, 9, 12]

In [4]:
np.random.seed(seed=1)
arr_1 = np.random.randint(15, 35, (2, 3))
arr_1

array([[20, 26, 27],
       [23, 24, 26]], dtype=int32)

In [44]:
np.std(arr_1)

np.float64(2.3570226039551585)

In [45]:
np.mean(arr_1)

np.float64(24.333333333333332)

In [47]:
np.max(arr_1)

np.int32(27)

In [48]:
np.sum(arr_1)

np.int64(146)

In [6]:
arr_1

array([[20, 26, 27],
       [23, 24, 26]], dtype=int32)

In [7]:
np.sum(arr_1, axis=1)

array([73, 73])

In [46]:
np.median(arr_1)

np.float64(25.0)

In [20]:
np.random.seed(seed=1)
arr_2 = np.random.randint(9, 15, (2, 3))
arr_2

array([[14, 12, 13],
       [ 9, 10, 12]], dtype=int32)

In [29]:
arr_2 *20

array([[280, 240, 260],
       [180, 200, 240]], dtype=int32)

In [33]:
arr_1 **2

array([[400, 676, 729],
       [529, 576, 676]], dtype=int32)

In [39]:
np.exp2(arr_1)

array([[1.04857600e+06, 6.71088640e+07, 1.34217728e+08],
       [8.38860800e+06, 1.67772160e+07, 6.71088640e+07]])

In [41]:
np.log(arr_1)

array([[2.99573227, 3.25809654, 3.29583687],
       [3.13549422, 3.17805383, 3.25809654]])

In [42]:
np.log2(arr_1)

array([[4.32192809, 4.70043972, 4.7548875 ],
       [4.52356196, 4.5849625 , 4.70043972]])

In [34]:
arr_1 + arr_2

array([[34, 38, 40],
       [32, 34, 38]], dtype=int32)

In [36]:
1/arr_2

array([[0.07142857, 0.08333333, 0.07692308],
       [0.11111111, 0.1       , 0.08333333]])

In [50]:
np.min(arr_2)

np.int32(9)

- you can do intra array operation. Learn more about it.
- also learn about corrcoef
