In [2]:
import numpy as np

In [6]:
np.random.seed(seed=1)
arr = np.random.randint(0, 10, 9)
arr

array([5, 8, 9, 5, 0, 0, 1, 7, 6], dtype=int32)

In [8]:
arr[-3]

np.int32(1)

In [14]:
arr[:-4]

array([5, 8, 9, 5, 0], dtype=int32)

In [17]:
arr[-4:-1]

array([0, 1, 7], dtype=int32)

**2D Arrays

In [20]:
np.random.seed(seed=0)
arr = np.random.randint(80, 300, (3,4))
arr

array([[252, 127, 197, 272],
       [147, 275, 183,  89],
       [291, 101, 116, 167]], dtype=int32)

In [21]:
arr[:, -3]

array([127, 275, 101], dtype=int32)

In [22]:
arr[-2,:]

array([147, 275, 183,  89], dtype=int32)